#!/bin/env bash
# This script displays the content of the file /etc/passwd
# It only displays the username, user id, and home directory path for each user

while IFS=: read -r user _ uid _ _ home _; do
  printf "Username: %s\nUser ID: %s\nHome directory: %s\n\n" "$user" "$uid" "$home"
done < /etc/passwd
