#!/bin/env bash
#This script displays The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

for file in *
do
    if [[ ! "$file" =~ ^\. ]]; then # check if file is not a hidden file
        name=$(echo "$file" | cut -d '-' -f 2-) # extract the part after the first dash
        echo "- $name"
    fi
done
